version: '3.8'

services:
  app-dev:
    container_name: bookit-app-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ~/.m2:/root/.m2
    networks:
      - bookit-dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - KEY_ID=${KEY_ID}
      - SECRET_KEY=${SECRET_KEY}
      - REGION=${REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - BUCKET=${BUCKET}
      - AUTH=${AUTH}
      - MODEL_URI=${MODEL_URI}
      - SYSTEM_TEXT=${SYSTEM_TEXT}
      - SYSTEM_TEXT_ANALYZE=${SYSTEM_TEXT_ANALYZE}
      - API_URL=${API_URL}
      - FOLDER_ID=${FOLDER_ID}
      - TZ=Europe/Moscow
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_SENDER_NAME=${MAIL_SENDER_NAME}
      - MAIL_SSL_ENABLE=${MAIL_SSL_ENABLE}
      - MAIL_STARTTLS_ENABLE=${MAIL_STARTTLS_ENABLE}
      - MAIL_FROM_EMAIL=${MAIL_FROM_EMAIL}
      - SPRING_RABBITMQ_HOST=rabbitmq-dev
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER:-guest}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - MESSAGING_ENABLED=true
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}

      #  tg-bot
      - TG_BOT_ENABLED=true
      - BOT_TOKEN=${BOT_TOKEN}
      - PHOTO_URL=${PHOTO_URL}
      - WEBSITE=${WEBSITE}
      - BOT_USERNAME=${BOT_USERNAME}

    depends_on:
      rabbitmq-dev:
        condition: service_healthy

  rabbitmq-dev:
    container_name: bookit-rabbitmq-dev
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    volumes:
      - rabbitmq_data_dev:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bookit-dev

volumes:
  rabbitmq_data_dev:

networks:
  bookit-dev:
    driver: bridge