version: '3.8'

services:
  app-test:
    container_name: bookit-app-test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ~/.m2:/root/.m2
    networks:
      - bookit-test
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - KEY_ID=${KEY_ID}
      - SECRET_KEY=${SECRET_KEY}
      - REGION=${REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - BUCKET=${BUCKET}
      - AUTH=${AUTH}
      - MODEL_URI=${MODEL_URI}
      - SYSTEM_TEXT=${SYSTEM_TEXT}
      - SYSTEM_TEXT_ANALYZE=${SYSTEM_TEXT_ANALYZE}
      - API_URL=${API_URL}
      - FOLDER_ID=${FOLDER_ID}
      - TZ=Europe/Moscow
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_SENDER_NAME=${MAIL_SENDER_NAME}
      - MAIL_SSL_ENABLE=${MAIL_SSL_ENABLE}
      - MAIL_STARTTLS_ENABLE=${MAIL_STARTTLS_ENABLE}
      - MAIL_FROM_EMAIL=${MAIL_FROM_EMAIL}
      - SPRING_RABBITMQ_HOST=localhost
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER:-guest}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - MESSAGING_ENABLED=false


networks:
  bookit-test:
    driver: bridge