version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - KEY_ID=${KEY_ID}
      - SECRET_KEY=${SECRET_KEY}
      - REGION=${REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - BUCKET=${BUCKET}
      - AUTH=${AUTH}
      - MODEL_URI=${MODEL_URI}
      - SYSTEM_TEXT=${SYSTEM_TEXT}
      - SYSTEM_TEXT_ANALYZE=${SYSTEM_TEXT_ANALYZE}
      - API_URL=${API_URL}
      - FOLDER_ID=${FOLDER_ID}

  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: