spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    backup:
      command: pg_dump -U ${spring.datasource.username} -h localhost -p 5432 -d ${spring.datasource.name} -F c -f
      restore-command: pg_restore -U ${spring.datasource.username} -h localhost -p 5432 -d ${spring.datasource.name} -c

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration/prod
    baseline-on-migrate: true
    validate-on-migrate: false
    driver-class-name: org.postgresql.Driver
    baseline-version: 3

bookit:
  app:
    jwtSecret: bookItSecretKey123456789012345678901234567890123456789012345678901234567890
    jwtExpirationMs: 5h