spring:
  datasource:
    url: jdbc:postgresql://db:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        log:
          mask_data: true
  flyway:
    enabled: false
    locations: classpath:db/migration/prod
    baseline-on-migrate: true
    validate-on-migrate: false
    driver-class-name: org.postgresql.Driver
    baseline-version: 3

bookit:
  app:
    jwtSecret: bookItSecretKey123456789012345678901234567890123456789012345678901234567890
    jwtExpirationMs: 18000000

logging:
  level:
    org.springframework: WARN
    org.springframework.web: WARN
    org.springframework.transaction: WARN
    org.springframework.security: WARN
    org.springframework.security.web.FilterChainProxy: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: OFF
    org.hibernate.stat: OFF
    org.springframework.jdbc.core.JdbcTemplate: WARN
    org.springframework.jdbc.core.StatementCreatorUtils: OFF
    org.flywaydb: OFF
    ru.tbank.bookit: INFO
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [%X{traceId}] - %msg%n"
  file:
    name: /var/log/book-it/prod.log
    max-history: 30
    max-size: 100MB
    rotate-on-startup: true
    logback:
      rollingpolicy:
        clean-history-on-start: false
        file-name-pattern: /var/log/book-it/prod.%d{yyyy-MM-dd}.%i.log