spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coworking_db
    driver-class-name: org.postgresql.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
booking:
  availability: 10