spring:
  profiles:
    active: dev
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  default-produces-media-type: application/json

booking:
  max-days-forward: 30
  start-work: 8
  end-work: 21