spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration/prod
    baseline-on-migrate: true
    validate-on-migrate: false
    driver-class-name: org.postgresql.Driver
    baseline-version: 3