spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true

  flyway:
    enabled: true
    locations: classpath:db/migration/prod
    baseline-on-migrate: true
    validate-on-migrate: false
    driver-class-name: org.postgresql.Driver
    baseline-version: 3