spring:
  datasource:
    url: jdbc:postgresql://db:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration/prod
    baseline-on-migrate: true
    validate-on-migrate: false
    driver-class-name: org.postgresql.Driver
    baseline-version: 3

bookit:
  app:
    jwtSecret: bookItSecretKey123456789012345678901234567890123456789012345678901234567890
    jwtExpirationMs: 18000000