
ALTER TABLE "PUBLIC"."NEWS"
    ADD COLUMN "SHORT_DESCRIPTION" VARCHAR(500);

ALTER TABLE "PUBLIC"."NEWS"
    RENAME COLUMN "DESCRIPTION" TO "FULL_DESCRIPTION";

ALTER TABLE "PUBLIC"."NEWS"
    ALTER COLUMN "FULL_DESCRIPTION" TYPE VARCHAR(2000);

COMMENT ON COLUMN "PUBLIC"."NEWS"."FULL_DESCRIPTION" IS 'Полное описание новости (до 2000 символов)';
COMMENT ON COLUMN "PUBLIC"."NEWS"."SHORT_DESCRIPTION" IS 'Краткое описание новости (до 500 символов)';

ALTER TABLE "PUBLIC"."EVENTS"
    ADD COLUMN "SHORT_DESCRIPTION" VARCHAR(500);

ALTER TABLE "PUBLIC"."EVENTS"
    RENAME COLUMN "DESCRIPTION" TO "FULL_DESCRIPTION";

ALTER TABLE "PUBLIC"."EVENTS"
    ALTER COLUMN "FULL_DESCRIPTION" TYPE VARCHAR(2000);

COMMENT ON COLUMN "PUBLIC"."EVENTS"."FULL_DESCRIPTION" IS 'Полное описание новости (до 2000 символов)';
COMMENT ON COLUMN "PUBLIC"."EVENTS"."SHORT_DESCRIPTION" IS 'Краткое описание новости (до 500 символов)';