ALTER TABLE "PUBLIC"."EVENTS"
    ADD COLUMN IF NOT EXISTS "REQUIRES_APPLICATION" BOOLEAN DEFAULT TRUE NOT NULL;

COMMENT ON COLUMN "PUBLIC"."EVENTS"."REQUIRES_APPLICATION" IS 'Флаг: для участия требуется заявка пользователя';

