name: CI

on:
  push:
  pull_request:
    branches:
      - main
      - remote_deploy

env:
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Test with Maven
        run: mvn clean test

      - name: Install SSH key
        uses: webfactory/ssh-agent@0.9.0
        with:
          ssh-private-key: $SSH_KEY

      - name: Deploy on remote server
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
          cd ./bookit-back &&
          git checkout main &&
          git merge &&
          sudo docker-compose -f docker-dev.yaml up --build -d
          "
